server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true




spring:
  profiles:
    group:
      "local": "local, common"
      "development": "development, common"
    active: local

---
# ??
spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    generate-ddl: false
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  servlet:
    multipart:
      file-size-threshold: 1MB
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${{ secrets.DATASOURCE_URL }}
#    username: ${{ secrets.DATASOURCE_USERNAME }}
#    password: ${{ secrets.DATASOURCE_PASSWORD }}

jwt:
  secret: ${{ secrets.JWT_SECRET }}
mybatis:
  mapper-locations: mybatis/**/*.xml

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      #  설정 CloudForamtion 없이도 프로젝트 시작할 수 있도록 설정
      auto: false
#    credentials:
#      access-key: ${{ secrets.AWS_ACCESS_KEY }}
#      secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#    s3:
#      # 파일 업로드 및 다운로드 될 버킷
#      buket: ${{ secrets.AWS_S3_BUCKET }}

logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          # ?? ?? ?? ?? ??
          EC2MetadataUtils: error


---
# ?? ??? ??
spring:
  environment: "local"
  config:
    activate:
      on-profile: "local"
  file-dir: /src/main/resources/files/

---
# ?? ??? ??
spring:
  environment: "development"
  config:
    activate:
      on-profile: "development"
  file-dir: /src/ec2-user/files/



