name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set secret yml file
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application.yml
      env:
        spring.datasource.url: ${{ secrets.DATASOURCE_URL }} 
        spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }} 
        spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }} 
        jwt.secret: ${{ secrets.JWT_SECRET }}
        cloud.aws.credentials.accessKey: ${{ secrets.AWS_ACCESS_KEY }}
        cloud.aws.credentials.secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        cloud.aws.s3.bucket: ${{ secrets.AWS_S3_BUCKET }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    
    
